added some styling
janneserichsen/CapStone-Graffstar pull request #11
Opened 2023-02-06 15:07 UTC by janneserichsen

2023-02-06 15:43 UTC, NikRoe requested changes
Hi Jannes,

left a few notes.

We neither work with classic CSS not inline styling, but with styled components. 

Please remove all CSS classes as well as inline styling and work with styled components instead.

2023-02-06 15:43 UTC, NikRoe commented on components/comment/Form.js
> +    <form className="form" onSubmit={handleSubmit}>
we don't work with classNames but with styled components.
See our session handout [as reference](https://github.com/neuefische/web-bo-22-2/blob/main/sessions/react-styled-components/react-styled-components.md).

2023-02-06 15:43 UTC, NikRoe commented on components/comment/Graffitipost.js
> +                }}
you should use styled components instead
```suggestion
```

2023-02-06 15:43 UTC, NikRoe commented on components/comment/Graffitipost.js
> +                }}
you should use styled components instead
```suggestion
```

2023-02-06 15:43 UTC, NikRoe commented on components/comment/Graffitipost.js
> +              <section
this section appears to only serve a styling purpose and has no semantic purpose here. You should replace it with a div

2023-02-06 15:43 UTC, NikRoe commented on components/comment/Graffitipost.js
> +                }}
```suggestion
```

2023-02-06 15:43 UTC, NikRoe commented on package.json
> +    "uuid": "^9.0.0"
2 dependencies to create unique ids? You should remove one of those

2023-02-06 15:43 UTC, NikRoe commented on pages/navbar/index.js
> +        }}
use styled components instead

```suggestion
```

2023-02-06 15:43 UTC, NikRoe commented on pages/navbar/index.js
> +          }}
```suggestion
```

2023-02-06 15:43 UTC, NikRoe commented on pages/navbar/index.js
> +          }}
```suggestion
```

2023-02-06 15:43 UTC, NikRoe commented on pages/navbar/index.js
> +          }}
```suggestion
```

2023-02-06 15:43 UTC, NikRoe commented on pages/profile/index.js
> +          }}
use styled components instead

```suggestion
```

2023-02-06 15:43 UTC, NikRoe commented on pages/profile/index.js
> +          }}
```suggestion
```

2023-02-06 15:43 UTC, NikRoe commented on pages/profile/index.js
> +          }}
```suggestion
```

2023-02-06 15:43 UTC, NikRoe commented on styles.js
> +  }
you can extend the Image component with styled components and should do so.

```suggestion
```

see [this as reference](https://github.com/neuefische/web-bo-22-2/blob/main/sessions/react-styled-components/react-styled-components.md#styling-a-custom-component)

2023-02-06 15:43 UTC, NikRoe commented on styles.js
> +import Link from "next/link";
```suggestion
```

2023-02-07 16:30 UTC, shebtastic requested changes

2023-02-07 16:30 UTC, shebtastic commented on components/comment/Form.js
> +        <button type="submit" className="form__button">
since you're mostly using `styled-components` anyway, you should omit the `classNames` and style the tags instead.

2023-02-07 16:30 UTC, shebtastic commented on components/comment/Graffitipost.js
> +`;
is there a reason why these components are restyled here, instead of styling within the component?

2023-02-07 16:30 UTC, shebtastic commented on components/comment/Graffitipost.js
> +const comments = [];
is this variable unused?

2023-02-07 16:30 UTC, shebtastic commented on components/comment/List.js
> +      <ul className="tag-list">
same for `className` here as above

2023-02-07 16:30 UTC, shebtastic commented on package.json
> +    "uuid": "^9.0.0"
i am seconding this

2023-02-07 16:30 UTC, shebtastic commented on pages/navbar/index.js
>      <>
this is an unnecessary fragment

2023-02-07 16:30 UTC, shebtastic commented on styles.js
> +  }
please remove this code section as suggested and style the `Image`-component directly.
i assume you were looking for `[object-fit](https://developer.mozilla.org/en-US/docs/Web/CSS/object-fit)` instead of justify content.

2023-02-07 16:30 UTC, shebtastic commented on components/comment/Form.js
> +export default function Form({ onSubmit }) {
is there a reason why _all_ your components are in the `components/comment` folder instead of `components` directly?

2023-02-07 21:26 UTC, merged